### ISSUE TITLE
Jest fails

### ISSUE THREAD

**Issue by mrclay** [RxNT/react-jsonschema-form-conditionals#52] opened 2018-02-21 15:59 UTC
```
TypeError: Cannot read property 'cacheDirectory' of undefined
    at /Users/sclay/work/react-jsonschema-form-conditionals/node_modules/jest-cli/build/cli/index.js:268:69
    at Generator.next (<anonymous>)
    at step (/Users/sclay/work/react-jsonschema-form-conditionals/node_modules/jest-cli/build/cli/index.js:45:2466)
    at /Users/sclay/work/react-jsonschema-form-conditionals/node_modules/jest-cli/build/cli/index.js:45:2696
    at new Promise (<anonymous>)
    at /Users/sclay/work/react-jsonschema-form-conditionals/node_modules/jest-cli/build/cli/index.js:45:2377
    at Promise.all.configs.map (/Users/sclay/work/react-jsonschema-form-conditionals/node_modules/jest-cli/build/cli/index.js:278:51)
    at Array.map (<anonymous>)
    at /Users/sclay/work/react-jsonschema-form-conditionals/node_modules/jest-cli/build/cli/index.js:267:13
    at Generator.next (<anonymous>)
```
Even explicitly setting jest.cacheDirectory in package.json made no change. Any ideas?

**Comment by mavarazy** [comment] 2018-02-27 14:01
@mrclay Thank you for finding this.

Is this refers to travis configuration issue? (It was using node 6 instead of 8), otherwise I've removed node_modules directory and ran `yarn` & `yarn test` and it worked just fine for me.
If you have steps to reproduce, it would be great.

**Comment by mavarazy** [comment] 2018-04-05 06:48
Closing for now, since travis is working just fine.

**Closed by mavarazy** 2018-04-05 06:48 UTC

**Comment by theluk** [comment] 2018-07-08 17:44
this still happens. just simply doing following

# git clone ...
# npm install
# npm run test

**Comment by theluk** [comment] 2018-07-08 18:21
it seems you installed using yarn something more than is actually defined in the package.json. Is it possible? 

in yarn.lock you have
```
jest-config@^21.2.1
```
while in the package.json and lock

```
 "jest-config": { "version": "20.0.4" }
```

thats just one example. 

with yarn it works.
